-- ===== events: 高写入量的原始事件表 =====
-- 建议：如果数据量非常大，考虑 PARTITION BY RANGE (slot) 或按时间字段分区
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot BIGINT NOT NULL,
    tx_sig TEXT NOT NULL,
    mint_pubkey VARCHAR(44) NOT NULL,
    account_pubkey VARCHAR(44) NOT NULL,
    owner_pubkey VARCHAR(44) NOT NULL,
    -- 如果 delta 可能超出 64-bit，请使用 NUMERIC(38,12) 或更高精度，
    -- 38位，小数允许为12位
    delta NUMERIC(38,12) NOT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    -- 唯一性约束，如果不是reset sql，而是add的话，就不是使用这个语句了，应该使用ALTER TABLE
    CONSTRAINT events_tx_sig_account_pubkey_key UNIQUE (tx_sig, account_pubkey)
);

-- ===== token_accounts: 每个 account 的当前快照 =====
CREATE TABLE token_accounts (
    acct_pubkey VARCHAR(44) PRIMARY KEY,     -- 若固定长度建议 VARCHAR(n)
    mint_pubkey VARCHAR(44) NOT NULL,
    owner_pubkey VARCHAR(44) NOT NULL,
    balance NUMERIC(38,12) NOT NULL,          -- 若可用 BIGINT 建议改为 BIGINT
    last_updated_slot BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 仅当业务频繁按 mint_pubkey 或 owner_pubkey 查询时创建（会增加写入成本）
CREATE INDEX idx_token_accounts_mint_pubkey ON token_accounts (mint_pubkey);
CREATE INDEX idx_token_accounts_owner_pubkey ON token_accounts (owner_pubkey);


-- ===== holders: (mint, owner) 级别聚合快照 =====
CREATE TABLE holders (
    mint_pubkey VARCHAR(44) NOT NULL,
    owner_pubkey VARCHAR(44) NOT NULL,
    balance NUMERIC(38,12) NOT NULL,
    last_updated_slot BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (mint_pubkey, owner_pubkey)
);
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_holders_mint ON holders (mint_pubkey);

-- ===== mint_stats: 每个 mint 的聚合统计 =====
CREATE TABLE mint_stats (
    mint_pubkey TEXT PRIMARY KEY,
    holder_count BIGINT NOT NULL,
    last_updated_slot BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===== tracked_mints: 统计哪些已经build_baselined的代币 =====
CREATE TABLE tracked_mints (
    mint_pubkey VARCHAR(44) PRIMARY KEY,
    baseline_slot BIGINT,
    status TEXT CHECK(status IN ('baseline_building', 'catching_up', 'synced')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);